import type { Club } from './tipos';

/**
 * Los clubes del mundo.
 *
 *   prestigio    peso del club: historia, hinchada y proyección internacional.
 *                Es lo que te reconocen por haber jugado ahí.
 *   presupuesto  capacidad de pagar, relativa dentro de su liga.
 *   hinchada     tamaño y exigencia. Los grandes dan más fama y aprietan más.
 *
 * Los tres son calibración, no datos duros: están puestos a ojo para que la
 * escalera de la carrera tenga sentido, y se tocan sin miedo si el balance lo
 * pide.
 */

const c = (
	id: string,
	ligaId: string,
	nombre: string,
	ciudad: string,
	prestigio: number,
	presupuesto: number,
	hinchada: number
): Club => ({ id, ligaId, nombre, ciudad, prestigio, presupuesto, hinchada });

export const clubes: Club[] = [
	// === ARGENTINA · Liga Profesional =======================================
	c('ar-river', 'ar-1', 'River Plate', 'Buenos Aires', 88, 95, 98),
	c('ar-boca', 'ar-1', 'Boca Juniors', 'Buenos Aires', 88, 92, 100),
	c('ar-racing', 'ar-1', 'Racing Club', 'Avellaneda', 74, 72, 84),
	c('ar-independiente', 'ar-1', 'Independiente', 'Avellaneda', 74, 62, 82),
	c('ar-sanlorenzo', 'ar-1', 'San Lorenzo', 'Buenos Aires', 70, 55, 78),
	c('ar-velez', 'ar-1', 'Vélez Sarsfield', 'Buenos Aires', 68, 60, 62),
	c('ar-estudiantes', 'ar-1', 'Estudiantes de La Plata', 'La Plata', 68, 66, 64),
	c('ar-gimnasia', 'ar-1', 'Gimnasia y Esgrima La Plata', 'La Plata', 55, 42, 66),
	c('ar-newells', 'ar-1', "Newell's Old Boys", 'Rosario', 64, 52, 74),
	c('ar-central', 'ar-1', 'Rosario Central', 'Rosario', 64, 55, 76),
	c('ar-talleres', 'ar-1', 'Talleres', 'Córdoba', 62, 64, 70),
	c('ar-belgrano', 'ar-1', 'Belgrano', 'Córdoba', 55, 50, 66),
	c('ar-instituto', 'ar-1', 'Instituto', 'Córdoba', 45, 38, 52),
	c('ar-lanus', 'ar-1', 'Lanús', 'Lanús', 58, 52, 54),
	c('ar-banfield', 'ar-1', 'Banfield', 'Banfield', 50, 42, 50),
	c('ar-huracan', 'ar-1', 'Huracán', 'Buenos Aires', 54, 44, 62),
	c('ar-argentinos', 'ar-1', 'Argentinos Juniors', 'Buenos Aires', 54, 46, 48),
	c('ar-defensa', 'ar-1', 'Defensa y Justicia', 'Florencio Varela', 48, 44, 38),
	c('ar-tigre', 'ar-1', 'Tigre', 'Victoria', 44, 38, 44),
	c('ar-godoycruz', 'ar-1', 'Godoy Cruz', 'Mendoza', 46, 42, 50),
	c('ar-union', 'ar-1', 'Unión', 'Santa Fe', 45, 40, 52),
	c('ar-colon', 'ar-1', 'Colón', 'Santa Fe', 45, 38, 56),
	c('ar-atltucuman', 'ar-1', 'Atlético Tucumán', 'San Miguel de Tucumán', 44, 40, 54),
	c('ar-platense', 'ar-1', 'Platense', 'Vicente López', 40, 34, 40),

	// === ARGENTINA · Primera Nacional (el Ascenso) ==========================
	c('ar2-moron', 'ar-2', 'Deportivo Morón', 'Morón', 28, 26, 38),
	c('ar2-almagro', 'ar-2', 'Almagro', 'José Ingenieros', 26, 24, 32),
	c('ar2-chacarita', 'ar-2', 'Chacarita Juniors', 'San Martín', 34, 28, 48),
	c('ar2-allboys', 'ar-2', 'All Boys', 'Buenos Aires', 28, 24, 40),
	c('ar2-chicago', 'ar-2', 'Nueva Chicago', 'Buenos Aires', 28, 24, 42),
	c('ar2-ferro', 'ar-2', 'Ferro Carril Oeste', 'Buenos Aires', 36, 30, 46),
	c('ar2-atlanta', 'ar-2', 'Atlanta', 'Buenos Aires', 28, 26, 38),
	c('ar2-temperley', 'ar-2', 'Temperley', 'Temperley', 26, 24, 34),
	c('ar2-estudiantesrc', 'ar-2', 'Estudiantes de Río Cuarto', 'Río Cuarto', 24, 26, 28),
	c('ar2-sanmartint', 'ar-2', 'San Martín de Tucumán', 'San Miguel de Tucumán', 32, 30, 48),
	c('ar2-gimnasiajujuy', 'ar-2', 'Gimnasia de Jujuy', 'San Salvador de Jujuy', 30, 26, 44),
	c('ar2-quilmes', 'ar-2', 'Quilmes', 'Quilmes', 34, 28, 46),
	c('ar2-maipu', 'ar-2', 'Deportivo Maipú', 'Maipú', 24, 26, 30),
	c('ar2-alvarado', 'ar-2', 'Alvarado', 'Mar del Plata', 22, 24, 30),
	c('ar2-agropecuario', 'ar-2', 'Agropecuario', 'Carlos Casares', 20, 28, 22),
	c('ar2-defensoresbelgrano', 'ar-2', 'Defensores de Belgrano', 'Buenos Aires', 24, 22, 30),
	c('ar2-colegiales', 'ar-2', 'Colegiales', 'Munro', 20, 20, 26),
	c('ar2-tristansuarez', 'ar-2', 'Tristán Suárez', 'Ezeiza', 18, 20, 22),
	c('ar2-sanmiguel', 'ar-2', 'San Miguel', 'San Miguel', 20, 20, 28),
	c('ar2-losandes', 'ar-2', 'Los Andes', 'Lomas de Zamora', 24, 20, 34),

	// === BRASIL · Série A ====================================================
	c('br-flamengo', 'br-1', 'Flamengo', 'Río de Janeiro', 90, 96, 100),
	c('br-palmeiras', 'br-1', 'Palmeiras', 'São Paulo', 88, 94, 88),
	c('br-saopaulo', 'br-1', 'São Paulo', 'São Paulo', 84, 82, 86),
	c('br-corinthians', 'br-1', 'Corinthians', 'São Paulo', 84, 80, 94),
	c('br-santos', 'br-1', 'Santos', 'Santos', 80, 62, 74),
	c('br-fluminense', 'br-1', 'Fluminense', 'Río de Janeiro', 76, 70, 72),
	c('br-botafogo', 'br-1', 'Botafogo', 'Río de Janeiro', 74, 78, 74),
	c('br-vasco', 'br-1', 'Vasco da Gama', 'Río de Janeiro', 74, 66, 84),
	c('br-gremio', 'br-1', 'Grêmio', 'Porto Alegre', 80, 76, 82),
	c('br-internacional', 'br-1', 'Internacional', 'Porto Alegre', 78, 74, 80),
	c('br-atleticomg', 'br-1', 'Atlético Mineiro', 'Belo Horizonte', 78, 82, 82),
	c('br-cruzeiro', 'br-1', 'Cruzeiro', 'Belo Horizonte', 76, 74, 80),
	c('br-athletico', 'br-1', 'Athletico Paranaense', 'Curitiba', 68, 70, 58),
	c('br-coritiba', 'br-1', 'Coritiba', 'Curitiba', 56, 50, 58),
	c('br-bahia', 'br-1', 'Bahia', 'Salvador', 66, 76, 76),
	c('br-vitoria', 'br-1', 'Vitória', 'Salvador', 56, 48, 62),
	c('br-sport', 'br-1', 'Sport Recife', 'Recife', 58, 52, 68),
	c('br-fortaleza', 'br-1', 'Fortaleza', 'Fortaleza', 62, 62, 66),
	c('br-ceara', 'br-1', 'Ceará', 'Fortaleza', 54, 48, 60),
	c('br-goias', 'br-1', 'Goiás', 'Goiânia', 52, 46, 52),
	c('br-cuiaba', 'br-1', 'Cuiabá', 'Cuiabá', 42, 46, 34),
	c('br-bragantino', 'br-1', 'Bragantino', 'Bragança Paulista', 52, 72, 36),

	// === URUGUAY · Primera División ==========================================
	c('uy-penarol', 'uy-1', 'Peñarol', 'Montevideo', 78, 64, 92),
	c('uy-nacional', 'uy-1', 'Nacional', 'Montevideo', 78, 64, 90),
	c('uy-defensor', 'uy-1', 'Defensor Sporting', 'Montevideo', 52, 44, 46),
	c('uy-danubio', 'uy-1', 'Danubio', 'Montevideo', 50, 40, 44),
	c('uy-liverpool', 'uy-1', 'Liverpool', 'Montevideo', 48, 44, 40),
	c('uy-wanderers', 'uy-1', 'Montevideo Wanderers', 'Montevideo', 46, 38, 44),
	c('uy-racing', 'uy-1', 'Racing de Montevideo', 'Montevideo', 38, 32, 34),
	c('uy-river', 'uy-1', 'River Plate de Montevideo', 'Montevideo', 40, 34, 36),
	c('uy-cerro', 'uy-1', 'Cerro', 'Montevideo', 38, 30, 40),
	c('uy-rampla', 'uy-1', 'Rampla Juniors', 'Montevideo', 34, 26, 36),
	c('uy-progreso', 'uy-1', 'Progreso', 'Montevideo', 34, 28, 32),
	c('uy-bostonriver', 'uy-1', 'Boston River', 'Montevideo', 32, 30, 26),
	c('uy-plazacolonia', 'uy-1', 'Plaza Colonia', 'Colonia del Sacramento', 34, 30, 30),
	c('uy-cerrolargo', 'uy-1', 'Cerro Largo', 'Melo', 32, 30, 30),
	c('uy-maldonado', 'uy-1', 'Deportivo Maldonado', 'Maldonado', 30, 34, 24),
	c('uy-miramar', 'uy-1', 'Miramar Misiones', 'Montevideo', 30, 26, 30),

	// === CHILE · Primera División ============================================
	c('cl-colocolo', 'cl-1', 'Colo-Colo', 'Santiago', 76, 72, 94),
	c('cl-udechile', 'cl-1', 'Universidad de Chile', 'Santiago', 72, 66, 88),
	c('cl-ucatolica', 'cl-1', 'Universidad Católica', 'Santiago', 70, 68, 74),
	c('cl-unionespanola', 'cl-1', 'Unión Española', 'Santiago', 50, 46, 44),
	c('cl-palestino', 'cl-1', 'Palestino', 'Santiago', 46, 44, 40),
	c('cl-audax', 'cl-1', 'Audax Italiano', 'Santiago', 44, 42, 36),
	c('cl-magallanes', 'cl-1', 'Magallanes', 'Santiago', 40, 34, 40),
	c('cl-wanderers', 'cl-1', 'Santiago Wanderers', 'Valparaíso', 46, 36, 52),
	c('cl-everton', 'cl-1', 'Everton', 'Viña del Mar', 46, 42, 46),
	c('cl-ohiggins', 'cl-1', "O'Higgins", 'Rancagua', 44, 42, 44),
	c('cl-cobreloa', 'cl-1', 'Cobreloa', 'Calama', 46, 38, 48),
	c('cl-cobresal', 'cl-1', 'Cobresal', 'El Salvador', 40, 44, 26),
	c('cl-huachipato', 'cl-1', 'Huachipato', 'Talcahuano', 44, 44, 38),
	c('cl-nublense', 'cl-1', 'Ñublense', 'Chillán', 38, 38, 38),
	c('cl-iquique', 'cl-1', 'Deportes Iquique', 'Iquique', 36, 34, 36),
	c('cl-coquimbo', 'cl-1', 'Coquimbo Unido', 'Coquimbo', 38, 36, 42),
	c('cl-lacalera', 'cl-1', 'Unión La Calera', 'La Calera', 36, 38, 28),
	c('cl-laserena', 'cl-1', 'Deportes La Serena', 'La Serena', 36, 34, 38),

	// === MÉXICO · Liga MX ====================================================
	c('mx-america', 'mx-1', 'Club América', 'Ciudad de México', 84, 92, 92),
	c('mx-chivas', 'mx-1', 'Guadalajara', 'Guadalajara', 80, 80, 90),
	c('mx-cruzazul', 'mx-1', 'Cruz Azul', 'Ciudad de México', 76, 80, 80),
	c('mx-pumas', 'mx-1', 'Pumas UNAM', 'Ciudad de México', 72, 68, 76),
	c('mx-tigres', 'mx-1', 'Tigres UANL', 'San Nicolás de los Garza', 78, 90, 78),
	c('mx-monterrey', 'mx-1', 'Monterrey', 'Monterrey', 78, 92, 76),
	c('mx-santos', 'mx-1', 'Santos Laguna', 'Torreón', 64, 62, 58),
	c('mx-toluca', 'mx-1', 'Toluca', 'Toluca', 68, 72, 62),
	c('mx-leon', 'mx-1', 'León', 'León', 66, 70, 58),
	c('mx-pachuca', 'mx-1', 'Pachuca', 'Pachuca', 68, 74, 56),
	c('mx-necaxa', 'mx-1', 'Necaxa', 'Aguascalientes', 52, 54, 44),
	c('mx-atlas', 'mx-1', 'Atlas', 'Guadalajara', 58, 58, 56),
	c('mx-puebla', 'mx-1', 'Puebla', 'Puebla', 52, 48, 50),
	c('mx-queretaro', 'mx-1', 'Querétaro', 'Querétaro', 48, 48, 42),
	c('mx-tijuana', 'mx-1', 'Tijuana', 'Tijuana', 52, 56, 46),
	c('mx-mazatlan', 'mx-1', 'Mazatlán', 'Mazatlán', 40, 48, 34),
	c('mx-juarez', 'mx-1', 'Juárez', 'Ciudad Juárez', 42, 50, 36),
	c('mx-sanluis', 'mx-1', 'Atlético San Luis', 'San Luis Potosí', 44, 50, 40),

	// === ESPAÑA · LaLiga =====================================================
	c('es-realmadrid', 'es-1', 'Real Madrid', 'Madrid', 100, 100, 100),
	c('es-barcelona', 'es-1', 'Barcelona', 'Barcelona', 99, 92, 98),
	c('es-atletico', 'es-1', 'Atlético de Madrid', 'Madrid', 90, 88, 86),
	c('es-sevilla', 'es-1', 'Sevilla', 'Sevilla', 80, 68, 76),
	c('es-betis', 'es-1', 'Real Betis', 'Sevilla', 76, 70, 80),
	c('es-valencia', 'es-1', 'Valencia', 'Valencia', 80, 62, 82),
	c('es-villarreal', 'es-1', 'Villarreal', 'Villarreal', 76, 74, 56),
	c('es-athletic', 'es-1', 'Athletic Club', 'Bilbao', 80, 76, 84),
	c('es-realsociedad', 'es-1', 'Real Sociedad', 'San Sebastián', 76, 72, 72),
	c('es-celta', 'es-1', 'Celta de Vigo', 'Vigo', 64, 58, 64),
	c('es-getafe', 'es-1', 'Getafe', 'Getafe', 56, 52, 42),
	c('es-rayo', 'es-1', 'Rayo Vallecano', 'Madrid', 56, 50, 58),
	c('es-osasuna', 'es-1', 'Osasuna', 'Pamplona', 60, 54, 62),
	c('es-mallorca', 'es-1', 'Mallorca', 'Palma', 58, 54, 52),
	c('es-girona', 'es-1', 'Girona', 'Girona', 58, 60, 44),
	c('es-alaves', 'es-1', 'Alavés', 'Vitoria-Gasteiz', 52, 50, 48),
	c('es-espanyol', 'es-1', 'Espanyol', 'Barcelona', 62, 52, 62),
	c('es-laspalmas', 'es-1', 'Las Palmas', 'Las Palmas de Gran Canaria', 54, 48, 56),
	c('es-valladolid', 'es-1', 'Valladolid', 'Valladolid', 54, 46, 54),
	c('es-leganes', 'es-1', 'Leganés', 'Leganés', 46, 44, 40),

	// === ITALIA · Serie A ====================================================
	c('it-inter', 'it-1', 'Inter', 'Milán', 92, 88, 90),
	c('it-milan', 'it-1', 'Milan', 'Milán', 92, 84, 92),
	c('it-juventus', 'it-1', 'Juventus', 'Turín', 92, 88, 94),
	c('it-napoli', 'it-1', 'Napoli', 'Nápoles', 84, 82, 88),
	c('it-roma', 'it-1', 'Roma', 'Roma', 84, 78, 88),
	c('it-lazio', 'it-1', 'Lazio', 'Roma', 78, 72, 74),
	c('it-atalanta', 'it-1', 'Atalanta', 'Bérgamo', 78, 76, 60),
	c('it-fiorentina', 'it-1', 'Fiorentina', 'Florencia', 74, 70, 74),
	c('it-bologna', 'it-1', 'Bologna', 'Bolonia', 66, 64, 62),
	c('it-torino', 'it-1', 'Torino', 'Turín', 66, 58, 68),
	c('it-udinese', 'it-1', 'Udinese', 'Udine', 60, 56, 50),
	c('it-genoa', 'it-1', 'Genoa', 'Génova', 60, 54, 64),
	c('it-sassuolo', 'it-1', 'Sassuolo', 'Sassuolo', 54, 54, 36),
	c('it-empoli', 'it-1', 'Empoli', 'Empoli', 50, 48, 38),
	c('it-cagliari', 'it-1', 'Cagliari', 'Cagliari', 56, 50, 56),
	c('it-verona', 'it-1', 'Hellas Verona', 'Verona', 54, 48, 56),
	c('it-lecce', 'it-1', 'Lecce', 'Lecce', 50, 48, 52),
	c('it-monza', 'it-1', 'Monza', 'Monza', 48, 52, 36),
	c('it-parma', 'it-1', 'Parma', 'Parma', 58, 52, 54),
	c('it-como', 'it-1', 'Como', 'Como', 46, 62, 32),

	// === FRANCIA · Ligue 1 ===================================================
	c('fr-psg', 'fr-1', 'Paris Saint-Germain', 'París', 92, 100, 88),
	c('fr-marsella', 'fr-1', 'Marsella', 'Marsella', 82, 76, 94),
	c('fr-lyon', 'fr-1', 'Lyon', 'Lyon', 78, 70, 76),
	c('fr-monaco', 'fr-1', 'Mónaco', 'Mónaco', 76, 78, 48),
	c('fr-lille', 'fr-1', 'Lille', 'Lille', 72, 68, 68),
	c('fr-rennes', 'fr-1', 'Rennes', 'Rennes', 68, 70, 62),
	c('fr-niza', 'fr-1', 'Niza', 'Niza', 66, 68, 56),
	c('fr-lens', 'fr-1', 'Lens', 'Lens', 66, 62, 76),
	c('fr-nantes', 'fr-1', 'Nantes', 'Nantes', 62, 54, 66),
	c('fr-estrasburgo', 'fr-1', 'Estrasburgo', 'Estrasburgo', 56, 58, 56),
	c('fr-montpellier', 'fr-1', 'Montpellier', 'Montpellier', 56, 52, 50),
	c('fr-toulouse', 'fr-1', 'Toulouse', 'Toulouse', 56, 54, 52),
	c('fr-brest', 'fr-1', 'Brest', 'Brest', 50, 48, 46),
	c('fr-reims', 'fr-1', 'Reims', 'Reims', 52, 50, 46),
	c('fr-angers', 'fr-1', 'Angers', 'Angers', 46, 44, 40),
	c('fr-auxerre', 'fr-1', 'Auxerre', 'Auxerre', 50, 46, 44),
	c('fr-saintetienne', 'fr-1', 'Saint-Étienne', 'Saint-Étienne', 66, 54, 80),
	c('fr-lehavre', 'fr-1', 'Le Havre', 'Le Havre', 46, 42, 42),

	// === ALEMANIA · Bundesliga ===============================================
	c('de-bayern', 'de-1', 'Bayern Múnich', 'Múnich', 98, 98, 96),
	c('de-dortmund', 'de-1', 'Borussia Dortmund', 'Dortmund', 88, 84, 98),
	c('de-leipzig', 'de-1', 'RB Leipzig', 'Leipzig', 78, 86, 56),
	c('de-leverkusen', 'de-1', 'Bayer Leverkusen', 'Leverkusen', 82, 82, 66),
	c('de-eintracht', 'de-1', 'Eintracht Frankfurt', 'Fráncfort', 74, 72, 80),
	c('de-wolfsburgo', 'de-1', 'Wolfsburgo', 'Wolfsburgo', 66, 72, 48),
	c('de-gladbach', 'de-1', 'Borussia Mönchengladbach', 'Mönchengladbach', 70, 64, 74),
	c('de-stuttgart', 'de-1', 'Stuttgart', 'Stuttgart', 70, 66, 76),
	c('de-werder', 'de-1', 'Werder Bremen', 'Bremen', 68, 58, 74),
	c('de-hoffenheim', 'de-1', 'Hoffenheim', 'Sinsheim', 58, 66, 38),
	c('de-friburgo', 'de-1', 'Friburgo', 'Friburgo', 62, 58, 60),
	c('de-union', 'de-1', 'Unión Berlín', 'Berlín', 58, 56, 62),
	c('de-mainz', 'de-1', 'Mainz 05', 'Maguncia', 56, 54, 52),
	c('de-augsburgo', 'de-1', 'Augsburgo', 'Augsburgo', 52, 54, 48),
	c('de-bochum', 'de-1', 'Bochum', 'Bochum', 48, 44, 54),
	c('de-heidenheim', 'de-1', 'Heidenheim', 'Heidenheim', 42, 42, 36),
	c('de-stpauli', 'de-1', 'St. Pauli', 'Hamburgo', 52, 46, 70),
	c('de-kiel', 'de-1', 'Holstein Kiel', 'Kiel', 42, 40, 40),

	// === PORTUGAL · Primeira Liga ============================================
	c('pt-benfica', 'pt-1', 'Benfica', 'Lisboa', 86, 82, 94),
	c('pt-porto', 'pt-1', 'Porto', 'Oporto', 86, 80, 90),
	c('pt-sporting', 'pt-1', 'Sporting de Lisboa', 'Lisboa', 84, 80, 88),
	c('pt-braga', 'pt-1', 'Braga', 'Braga', 70, 66, 58),
	c('pt-guimaraes', 'pt-1', 'Vitória de Guimarães', 'Guimarães', 60, 54, 64),
	c('pt-boavista', 'pt-1', 'Boavista', 'Oporto', 54, 44, 52),
	c('pt-rioave', 'pt-1', 'Rio Ave', 'Vila do Conde', 48, 44, 40),
	c('pt-famalicao', 'pt-1', 'Famalicão', 'Vila Nova de Famalicão', 46, 46, 36),
	c('pt-gilvicente', 'pt-1', 'Gil Vicente', 'Barcelos', 44, 42, 38),
	c('pt-moreirense', 'pt-1', 'Moreirense', 'Moreira de Cónegos', 42, 40, 32),
	c('pt-arouca', 'pt-1', 'Arouca', 'Arouca', 42, 40, 32),
	c('pt-estoril', 'pt-1', 'Estoril', 'Estoril', 42, 42, 34),
	c('pt-casapia', 'pt-1', 'Casa Pia', 'Lisboa', 40, 40, 30),
	c('pt-santaclara', 'pt-1', 'Santa Clara', 'Ponta Delgada', 40, 38, 34),
	c('pt-nacional', 'pt-1', 'Nacional', 'Funchal', 40, 36, 34),
	c('pt-farense', 'pt-1', 'Farense', 'Faro', 38, 36, 34),
	c('pt-estrela', 'pt-1', 'Estrela da Amadora', 'Amadora', 36, 34, 32),
	c('pt-avs', 'pt-1', 'AVS', 'Vila das Aves', 34, 34, 26),

	// === PAÍSES BAJOS · Eredivisie ===========================================
	c('nl-ajax', 'nl-1', 'Ajax', 'Ámsterdam', 88, 80, 90),
	c('nl-psv', 'nl-1', 'PSV', 'Eindhoven', 82, 80, 80),
	c('nl-feyenoord', 'nl-1', 'Feyenoord', 'Róterdam', 80, 74, 88),
	c('nl-az', 'nl-1', 'AZ', 'Alkmaar', 66, 62, 54),
	c('nl-twente', 'nl-1', 'Twente', 'Enschede', 60, 56, 62),
	c('nl-utrecht', 'nl-1', 'Utrecht', 'Utrecht', 58, 54, 58),
	c('nl-vitesse', 'nl-1', 'Vitesse', 'Arnhem', 52, 46, 48),
	c('nl-heerenveen', 'nl-1', 'Heerenveen', 'Heerenveen', 50, 46, 46),
	c('nl-groningen', 'nl-1', 'Groningen', 'Groninga', 50, 46, 52),
	c('nl-nec', 'nl-1', 'NEC', 'Nimega', 48, 46, 46),
	c('nl-sparta', 'nl-1', 'Sparta Rotterdam', 'Róterdam', 46, 42, 44),
	c('nl-goahead', 'nl-1', 'Go Ahead Eagles', 'Deventer', 44, 40, 42),
	c('nl-fortuna', 'nl-1', 'Fortuna Sittard', 'Sittard', 40, 40, 36),
	c('nl-heracles', 'nl-1', 'Heracles', 'Almelo', 40, 38, 36),
	c('nl-zwolle', 'nl-1', 'PEC Zwolle', 'Zwolle', 42, 40, 40),
	c('nl-willem2', 'nl-1', 'Willem II', 'Tilburg', 44, 40, 44),
	c('nl-rkc', 'nl-1', 'RKC Waalwijk', 'Waalwijk', 38, 36, 32),
	c('nl-almere', 'nl-1', 'Almere City', 'Almere', 34, 34, 28),

	// === INGLATERRA · Premier League =========================================
	c('en-mancity', 'en-1', 'Manchester City', 'Mánchester', 94, 100, 82),
	c('en-arsenal', 'en-1', 'Arsenal', 'Londres', 92, 92, 92),
	c('en-liverpool', 'en-1', 'Liverpool', 'Liverpool', 96, 94, 98),
	c('en-manutd', 'en-1', 'Manchester United', 'Mánchester', 94, 90, 96),
	c('en-chelsea', 'en-1', 'Chelsea', 'Londres', 88, 94, 84),
	c('en-tottenham', 'en-1', 'Tottenham', 'Londres', 82, 84, 82),
	c('en-newcastle', 'en-1', 'Newcastle', 'Newcastle', 76, 86, 84),
	c('en-astonvilla', 'en-1', 'Aston Villa', 'Birmingham', 74, 78, 74),
	c('en-brighton', 'en-1', 'Brighton', 'Brighton', 64, 74, 54),
	c('en-westham', 'en-1', 'West Ham', 'Londres', 70, 74, 76),
	c('en-everton', 'en-1', 'Everton', 'Liverpool', 70, 66, 78),
	c('en-crystalpalace', 'en-1', 'Crystal Palace', 'Londres', 62, 66, 62),
	c('en-fulham', 'en-1', 'Fulham', 'Londres', 60, 66, 56),
	c('en-brentford', 'en-1', 'Brentford', 'Londres', 56, 64, 48),
	c('en-forest', 'en-1', 'Nottingham Forest', 'Nottingham', 64, 70, 68),
	c('en-bournemouth', 'en-1', 'Bournemouth', 'Bournemouth', 54, 62, 44),
	c('en-wolves', 'en-1', 'Wolverhampton', 'Wolverhampton', 60, 62, 58),
	c('en-leicester', 'en-1', 'Leicester', 'Leicester', 62, 62, 58),
	c('en-southampton', 'en-1', 'Southampton', 'Southampton', 56, 58, 56),
	c('en-ipswich', 'en-1', 'Ipswich', 'Ipswich', 46, 50, 46),

	// === TURQUÍA · Süper Lig =================================================
	c('tr-galatasaray', 'tr-1', 'Galatasaray', 'Estambul', 84, 86, 96),
	c('tr-fenerbahce', 'tr-1', 'Fenerbahçe', 'Estambul', 84, 88, 96),
	c('tr-besiktas', 'tr-1', 'Beşiktaş', 'Estambul', 80, 74, 92),
	c('tr-trabzonspor', 'tr-1', 'Trabzonspor', 'Trebisonda', 72, 66, 84),
	c('tr-basaksehir', 'tr-1', 'Başakşehir', 'Estambul', 62, 68, 34),
	c('tr-adanademir', 'tr-1', 'Adana Demirspor', 'Adana', 54, 58, 50),
	c('tr-konyaspor', 'tr-1', 'Konyaspor', 'Konya', 52, 50, 52),
	c('tr-alanyaspor', 'tr-1', 'Alanyaspor', 'Alanya', 48, 50, 36),
	c('tr-antalyaspor', 'tr-1', 'Antalyaspor', 'Antalya', 50, 50, 46),
	c('tr-kayserispor', 'tr-1', 'Kayserispor', 'Kayseri', 46, 46, 44),
	c('tr-sivasspor', 'tr-1', 'Sivasspor', 'Sivas', 46, 44, 44),
	c('tr-gaziantep', 'tr-1', 'Gaziantep FK', 'Gaziantep', 44, 46, 42),
	c('tr-rizespor', 'tr-1', 'Rizespor', 'Rize', 42, 42, 42),
	c('tr-kasimpasa', 'tr-1', 'Kasımpaşa', 'Estambul', 42, 44, 30),
	c('tr-samsunspor', 'tr-1', 'Samsunspor', 'Samsun', 44, 46, 50),
	c('tr-hatayspor', 'tr-1', 'Hatayspor', 'Antioquía', 40, 40, 38),
	c('tr-goztepe', 'tr-1', 'Göztepe', 'Esmirna', 46, 46, 52),
	c('tr-eyupspor', 'tr-1', 'Eyüpspor', 'Estambul', 36, 42, 28)
];
